name: test

on:
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - LICENSE
      - .gitignore
      - .npmignore
      - .editorconfig
      - .github/**
        
jobs:

  readyGo:

    runs-on: ubuntu-latest
      
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          registry-url: https://registry.npmjs.org/

      - name: before scripts
        run: |
          echo "Current branch: ${{ github.ref_name }}"
  
      - name: install
        run: |
          npm ci

      - name: test
        run: |
          npm run updateSnapshot
          npm run test:unit
          npm run test:e2e
  
      - name: build
        run: |
          npm run build
